import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Accordions from "../components/leftSideBar/Accordions";
import Header from "../components/leftSideBar/Header";
import IconButtons from "../components/leftSideBar/IconButtons";
import LoginButton from "../components/leftSideBar/LoginButton";
import HeroSection from "../components/main/HeroSection";
import NavBar from "../components/main/NavBar";
import SpotLight from "../components/main/SpotLight";
import MainSection from "../components/rightSideBar/MainSection";
import TopBar from "../components/rightSideBar/TopBar";

export default function Home() {
  const [uniSwap, setUniSwap] = useState(true);
  const [pancakeSwap, setPancakeSwap] = useState(false);
  const [quickSwap, setQuickSwap] = useState(false);
  const customProps = {
    uniSwap: uniSwap,
    setUniSwap: setUniSwap,
    pancakeSwap: pancakeSwap,
    setPancakeSwap: setPancakeSwap,
    quickSwap: quickSwap,
    setQuickSwap: setQuickSwap,
  };
  return (
    <div className="antialiased">
      <Head>
        <title>InvestDex | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <div className=" bg-[#22222f] w-[13vw] h-screen ">
          <Header />
          <IconButtons />
          <Accordions />
          <LoginButton />
        </div>
        <main className="bg-[#111118] w-[63vw] ">
          <NavBar />
          <HeroSection {...customProps} />
          <SpotLight />
        </main>
        <div className=" bg-[#22222f] w-[24vw] h-screen overflow-y-scroll">
          <TopBar {...customProps} />
          <MainSection {...customProps} />
        </div>
      </div>
    </div>
  );
}
